### ISSUE TITLE
为什么设置上限和日志里面显示不一样？

### ISSUE THREAD

**Issue by tamakyi** [shilx/acfun-live#1]
在config里面设置了数量限制为9，但是日志里面依然只有3个
直播间数量限制 9
设置了不看 []
显示详细直播信息 true
佩戴牌子的主播不观看 false
登录方式 账号
===
第 1 次检查直播状态 2021/02/16 23:59:29
用户xxx
当前佩戴 10 QQ星 qyqx
---
开播时间 2021/02/16 19:34:32 false
6级 (360/360) 
[1/3] 
---
开播时间 2021/02/16 21:06:38 false
6级 (360/360) 
[2/3] 
---
开播时间 2021/02/16 23:17:23 false
5级  (80/360)
[3/3]

**Comment by shilx** [comment]
改了设置，手动重启一下进程试试，我没有监听配置文件。。

**Comment by tamakyi** [comment]
> 改了设置，手动重启一下进程试试，我没有监听配置文件。。

我挂在pm2上，
pm2 restart无效 把服务器重启了也无效🙃

**Comment by shilx** [comment]
> > 改了设置，手动重启一下进程试试，我没有监听配置文件。。
> 
> 
> 
> 我挂在pm2上，
> 
> pm2 restart无效 把服务器重启了也无效🙃

有牌子并且正在直播的房间只有3个

**Comment by tamakyi** [comment]
> > > 改了设置，手动重启一下进程试试，我没有监听配置文件。。
> > 
> > 
> > 我挂在pm2上，
> > pm2 restart无效 把服务器重启了也无效🙃
> 
> 有牌子并且正在直播的房间只有3个

还真有可能🙃再多D几个牌子试试看 谢谢😀有这个程序DD很幸福
