### ISSUE TITLE
|ω・´)

### ISSUE THREAD

**Issue by Sto1enDance** [shilx/acfun-live#18]
请问一下是否可以出一个面向小白的简略教学,或者该去哪里学习相关知识呢 |ω・´)

**Comment by shilx** [comment]
懒人包出来辽~下载并解压后，在config.json里面填入你的账号密码，然后双击acfunlive.exe运行即可！
[下载点我](https://github.91chifun.workers.dev/https://github.com//shilx/acfun-live/releases/download/v1.3.3-forWin/acfunlive.zip)
