### ISSUE TITLE
运行时提示Error，但程序能使用

### ISSUE THREAD

**Issue by albert9liang** [shilx/acfun-live#39]
当前版本：1.4.0，已是最新
= config.json config 已读取 =
调试模式 false
每天0~1点自动重启 30 00 00 * * *
每(分钟)检查直播 10
自动点赞已关闭
异步操作最多等待(分钟) 5
使用OBS弹幕工具监控 false
设置了不看 []
显示详细直播信息 true
佩戴牌子的主播不观看 false
监控未关注但是有牌子的主播 true
服务器矩阵配置 [ 0 ]
当前第 0 台
开播通知 false
🤖 定时重启工具运行中，规则：30 00 00 * * *
puppeteer launched，Cookie状态： true
登录方式 Cookie
===
第 1 次检查直播状态 2022-04-17 09:56:57
Fetch https://www.acfun.cn/rest/pc-direct/fansClub/fans/medal/list
获取 粉丝牌列表 done
Fetch https://live.acfun.cn/api/channel/list?count=1000&pcursor=0
获取 所有正在直播列表 done
顺序获取粉丝牌信息
Fetch https://www.acfun.cn/rest/pc-direct/fansClub/fans/medal/extraInfo?uperId=40656720
获取 40656720 当日时长 done
拥有牌子并且开播的直播间数 1
---
开播时间 2022-04-17 08:03:27
标题： 【早安D台】快洛的周日又到了！早起辛苦惹~
9级 艾哭鬼 (301/360) ✟艾米莉Emily✟ 40656720
[1/1] 进入直播
---
进入直播 ✟艾米莉Emily✟
进入直播间失败
Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'remove')
    at __puppeteer_evaluation_script__:9:60
    at ExecutionContext._evaluateInternal (C:\snapshot\acfun-live\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\snapshot\acfun-live\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async afterOpenRoom (C:\snapshot\acfun-live\pages.js:328:3)
    at async C:\snapshot\acfun-live\pages.js:296:9
    at async Promise.all (index 0)
    at async DDVup (C:\snapshot\acfun-live\pages.js:446:3)
第1次 handlePageError ✟艾米莉Emily✟ false
[错误为object并且有message] DOMException: The play() request was interrupted by a new load request.
第2次 handlePageError ✟艾米莉Emily✟ false
[错误为object并且有message] DOMException: The play() request was interrupted by a new load request.
第3次 handlePageError ✟艾米莉Emily✟ false
[错误为object并且有message] DOMException: The play() request was interrupted by a call to pause().
第4次 handlePageError ✟艾米莉Emily✟ false
[错误为object并且有message] Object
===

![image](https://user-images.githubusercontent.com/100278494/163697378-2cd8a0ae-974f-488a-84ff-4e5ac3b403e2.png)

**Comment by shilx** [comment]
`config.json`中的`useObsDanmaku`改为`true`就行了，这个问题预计在下个版本修复
