### ISSUE TITLE
是要关注后才能挂牌子吗

### ISSUE THREAD

**Issue by thmmjklp** [shilx/acfun-live#6]
因为没关注主播,测试的时候以为搭配的环境出问题了,后面折腾好几个小时后才发现是不是没关注的主播不检测牌子,结果还真的是.希望能有挂指定主播的更新(不强求)

**Comment by shilx** [comment]
- 没有关注的主播确实不会去监控  
- 没关注但是有牌子挂直播间还能涨经验吗？可以的话我摸鱼的时候写一下吧（咕咕咕

**Comment by thmmjklp** [comment]
> * 没有关注的主播确实不会去监控
> * 没关注但是有牌子挂直播间还能涨经验吗？可以的话我摸鱼的时候写一下吧（咕咕咕

会的,老单推人了,几十个牌子老难挂经验
